# Dependabot configuration file
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify version update strategy
    versioning-strategy: increase-if-necessary
    # Allow only minor and patch updates to minimize breaking changes
    allow:
      - dependency-type: "all"
        update-type: "semver-minor"
      - dependency-type: "all"
        update-type: "semver-patch"
    # Ignore major version updates for certain packages
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint-config-next"
        update-types: ["version-update:semver-major"]
    # Group dependencies updates
    groups:
      # Group all development dependencies together
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
      # Group all production dependencies together
      production:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "next-intl"
          - "chart.js"
          - "react-chartjs-2"
    # Remove reviewers configuration as it requires repository collaborator setup
    # Remove labels that don't exist yet

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow only minor and patch updates for actions
    allow:
      - dependency-type: "all"
        update-type: "semver-minor"
      - dependency-type: "all"
        update-type: "semver-patch"
