# Dependabot configuration file
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Configure version update preferences
    versioning-strategy: auto
    # Set version update limits
    open-pull-requests-limit: 10
    # Target version updates
    target-branch: "main"
    # Configure version range updates
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "@types/node"
        versions: ["22.x"]
      - dependency-name: "eslint"
        versions: ["9.x"]
      - dependency-name: "eslint-config-next"
        versions: ["15.x"]
    # Group dependencies updates
    groups:
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
      production:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "next-intl"
          - "chart.js"
          - "react-chartjs-2"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Set version update limits
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
